language: node_js
node_js:
  - "6"
branches:
  only:
    - master
before_script:
  - npm install -g webdriver-manager
  - npm install -g jasmine
  - npm install -g protractor
  - npm install phantomjs
  - npm run post-install
  - npm run selenium & 
  - npm run start &
  - sleep 3
